[package]
name = "ping"
version = "0.1.0"
authors = ["Addison Bean <addisonbean@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2"
ctrlc = { version = "3.0", features = ["termination"] }
pnet = "0.25"
